import React, { Component } from 'react'
import {
    Modal,
    Button,
    Table
} from 'react-bootstrap'

export default class View extends Component {
    constructor(props) {
        super(props)
    }

    render() {
        return (
            <Modal show={this.props.show}>
                <Button
                    variant="danger"
                    block={true}
                    type="button"
                    onClick={this.props.handleToggle}
                >
                    &times;
                </Button>
                <Modal.Header>
                    <Modal.Title className="text-primary">
                        View Student Data of {` ${this.props.student.name}`}
                    </Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Table>
                        <tr>
                            <th>
                                Student ID
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.id
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.name
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Born
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.born
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Gender
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.gender
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Degree
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.degree
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Faculty
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.faculty
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Major
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.major
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Semester
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.semester
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Email
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.email
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>
                                Phone Number
                            </th>
                            <th>
                                :
                            </th>
                            <td>
                                {
                                    this.props.student.phoneNumber
                                }
                            </td>
                        </tr>
                    </Table>
                </Modal.Body>
            </Modal>
        )
    }
}
